### ISSUE TITLE
ViewControl.convert_from_pinhole_camera_parameters produces 'nan's

### ISSUE THREAD

**Issue by StephanHasler** [isl-org/Open3D#1612]
**Description:**
When I set the camera parameters with the function
ViewControl.convert_from_pinhole_camera_parameters I get 'nan's in the resulting extrinsic parameters matrix.

**How to reproduce:**
I use following program:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import open3d

if __name__ == "__main__":
    # Initialize Visualizer and get its ViewControl.
    visualizer = open3d.visualization.Visualizer()
    visualizer.create_window(window_name="Open3D", width=800, height=800, left=50, top=50)
    view_control = visualizer.get_view_control()

    # Get and print the camera parameters.
    camera_parameters = view_control.convert_to_pinhole_camera_parameters()
    print("# Initial camera parameters\n{}\n{}".format(camera_parameters.extrinsic, camera_parameters.intrinsic.intrinsic_matrix))

    # Set the same parameters again.
    view_control.convert_from_pinhole_camera_parameters(camera_parameters)

    # Get and print the camera parameters again.
    camera_parameters = view_control.convert_to_pinhole_camera_parameters()
    print("\n# Changed camera parameters\n{}\n{}".format(camera_parameters.extrinsic, camera_parameters.intrinsic.intrinsic_matrix))
```

The output is:
```
# Initial camera parameters
[[ 1.  0.  0. -0.]
 [-0. -1. -0.  0.]
 [-0. -0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 692.82032303    0.          399.5       ]
 [   0.          692.82032303  399.5       ]
 [   0.            0.            1.        ]]

# Changed camera parameters
[[  1.   0.   0.  nan]
 [ -0.  -1.  -0.  nan]
 [ -0.  -0.  -1.  nan]
 [  0.   0.   0.   1.]]
[[ 692.82032303    0.          399.5       ]
 [   0.          692.82032303  399.5       ]
 [   0.            0.            1.        ]]
```

**Expectation:**
I would have expected, that the camera parameters would not change, especially that no 'nan' would be contained in the result. I also tested to set custom extrinsic parameters, in each case the 'nan' s were produced.

**Environment:**
 - OS: Ubuntu 18.04
 - Python version: 2.7.17
 - Open3D version: 0.9.0.0
 - Is this remote workstation?: no
 - How did you install Open3D?: pip

**Comment by syncle** [comment]
We are preparing a new visualization module with a new GUI, and this issue is resolved in that working branch. Could you try this branch? https://github.com/intel-isl/Open3D/tree/gui

**Comment by Leerw** [comment]
> We are preparing a new visualization module with a new GUI, and this issue is resolved in that working branch. Could you try this branch? https://github.com/intel-isl/Open3D/tree/gui

but build failed
```
~/lib/Open3D/build% uname -a
Linux CvGroup 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentCamera.cpp:30:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentCamera.cpp:30:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentCamera.cpp:30:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:813:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TextureUsage>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentCamera.cpp:30:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:813:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TextureUsage>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
src/Open3D/Visualization/CMakeFiles/Visualization.dir/build.make:902: recipe for target 'src/Open3D/Visualization/CMake
Files/Visualization.dir/Rendering/Filament/FilamentCamera.cpp.o' failed
make[2]: *** [src/Open3D/Visualization/CMakeFiles/Visualization.dir/Rendering/Filament/FilamentCamera.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/ImageFactory.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FilePCD.cpp.o
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEntitiesMods.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:811:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TargetBufferFlags>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEntitiesMods.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEntitiesMods.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:813:26: error: specialization of
template<class Enum> struct utils::EnableBitMaskOperators’ in different namespace [-fpermissive]
 template<> struct utils::EnableBitMaskOperators<filament::backend::TextureUsage>
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/DriverEnums.h:22:0,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/backend/Platform.h:22,
                 from /home/leerw/lib/Open3D/build/3rdparty_install/include/filament/filament/Engine.h:20,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEngine.h:29,
                 from /home/leerw/lib/Open3D/src/Open3D/Visualization/Rendering/Filament/FilamentEntitiesMods.cpp:29:
/home/leerw/lib/Open3D/build/3rdparty_install/include/filament/utils/BitmaskEnum.h:30:8: error:   from definition of ‘t
emplate<class Enum> struct utils::EnableBitMaskOperators’ [-fpermissive]
 struct EnableBitMaskOperators : public std::false_type { };
        ^~~~~~~~~~~~~~~~~~~~~~
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/IntersectionTest.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/KDTreeFlann.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/LineSet.cpp.o
src/Open3D/Visualization/CMakeFiles/Visualization.dir/build.make:926: recipe for target 'src/Open3D/Visualization/CMake
Files/Visualization.dir/Rendering/Filament/FilamentEngine.cpp.o' failed
make[2]: *** [src/Open3D/Visualization/CMakeFiles/Visualization.dir/Rendering/Filament/FilamentEngine.cpp.o] Error 1
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/LineSetFactory.cpp.o
src/Open3D/Visualization/CMakeFiles/Visualization.dir/build.make:950: recipe for target 'src/Open3D/Visualization/CMake
Files/Visualization.dir/Rendering/Filament/FilamentEntitiesMods.cpp.o' failed
make[2]: *** [src/Open3D/Visualization/CMakeFiles/Visualization.dir/Rendering/Filament/FilamentEntitiesMods.cpp.o] Erro
r 1
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/MeshBase.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FilePLY.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FilePNG.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/Octree.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/PointCloud.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/PointCloudCluster.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/PointCloudFactory.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/PointCloudSegmentation.cpp.o
CMakeFiles/Makefile2:1291: recipe for target 'src/Open3D/Visualization/CMakeFiles/Visualization.dir/all' failed
make[1]: *** [src/Open3D/Visualization/CMakeFiles/Visualization.dir/all] Error 2
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/Qhull.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FilePTS.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FileSTL.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FileTUM.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/RGBDImage.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/RGBDImageFactory.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/SurfaceReconstructionAlphaShape.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/SurfaceReconstructionBallPivoting.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/SurfaceReconstructionPoisson.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TetraMesh.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FileXYZ.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TetraMeshFactory.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TriangleMesh.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FileXYZN.cpp.o
[ 69%] Building CXX object src/Open3D/IO/CMakeFiles/IO.dir/FileFormat/FileXYZRGB.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TriangleMeshDeformation.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TriangleMeshFactory.cpp.o
[ 69%] Building C object src/Open3D/IO/CMakeFiles/IO.dir/__/__/__/3rdparty/rply/rply.c.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TriangleMeshSimplification.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/TriangleMeshSubdivide.cpp.o
[ 69%] Building C object src/Open3D/IO/CMakeFiles/IO.dir/__/__/__/3rdparty/liblzf/lzf_c.c.o
[ 69%] Building C object src/Open3D/IO/CMakeFiles/IO.dir/__/__/__/3rdparty/liblzf/lzf_d.c.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/VoxelGrid.cpp.o
[ 69%] Building CXX object src/Open3D/Geometry/CMakeFiles/Geometry.dir/VoxelGridFactory.cpp.o
[ 69%] Built target IO
[ 69%] Built target Geometry
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mbspng** [comment]
I am still getting nans in the extrinsics.


```
import numpy as np
import open3d
from open3d.visualization import ViewControl


np.set_printoptions(precision=2, suppress=True)


def main():
    vis = open3d.visualization.Visualizer()
    vis.create_window(visible=False)
    view_control: ViewControl = vis.get_view_control()

    vis.update_renderer()
    vis.poll_events()

    target = np.random.rand(3)

    extrinsics = construct_extrinsics(target)

    camera_parameters = view_control.convert_to_pinhole_camera_parameters()

    extrinsics_out = camera_parameters.extrinsic
    # no nans
    print(extrinsics_out)

    vis.update_renderer()
    vis.poll_events()

    camera_parameters.extrinsic = extrinsics
    result = view_control.convert_from_pinhole_camera_parameters(camera_parameters, allow_arbitrary=True)

    vis.update_renderer()
    vis.poll_events()

    assert result

    # no nans
    print(extrinsics)

    camera_parameters = view_control.convert_to_pinhole_camera_parameters()

    extrinsics_out = camera_parameters.extrinsic
    # nans
    print(extrinsics_out)


def construct_extrinsics(target: np.ndarray) -> np.ndarray:
    eye = np.zeros(3)
    forward = target - eye

    assert np.allclose(np.linalg.norm(forward), np.linalg.norm(target))

    forward /= np.linalg.norm(forward)

    up = np.array([0.0, 1.0, 0.0])
    right = np.cross(up, forward)
    up = np.cross(right, forward)

    up /= np.linalg.norm(up)
    right /= np.linalg.norm(right)

    assert up @ right < 1e-6
    assert up @ forward < 1e-6
    assert right @ forward < 1e-6

    rotation = np.array([right, up, forward])
    extrinsics = np.eye(4)
    extrinsics[:3, :3] = rotation
    extrinsics[:3, 3] = -(rotation @ eye)

    return extrinsics


if __name__ == "__main__":
    main()
```

`open3d v0.18.0`
