### ISSUE TITLE
More examples for detect_planar_patches

### ISSUE THREAD

**Issue by iegorval** [isl-org/Open3D#7003]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### My Question

Hello,

I am looking for more examples on different point clouds for `detect_planar_patches`. The method is absolutely unusable for me on a relatively simple pointcloud, either downsampled or not, with normal estimation from `open3d` as well. It either does not detect any plane or detects some random planes that do not seem to be related in any way with underlying surfaces.

If the method assumes that point cloud should have some specific features (point density, normal estimation quality etc), I think it is better to write it to documentation. It is also better to have more examples in order to give a feel whether the method would work or not.

I am detecting just simple rectangular box in the scene and it amazes me that this method fails so strongly even after trying different parameters set and original author's GUI in Qt.

Also, is there some alternative in `open3d` that is planned?

Thanks.

Best regards,
Valeria

**Comment by iegorval** [comment]
@rxba That is great info, thanks, will check it!

**Comment by iegorval** [comment]
> Hey @iegorval , I can confirm that this method did not produce good results for me either. However, while researching for similar issues to link to you (namely #6550 and discussion #6233 ), I realized that PR #6608 is probably the fix for this. This was merged into `main` in March, so it's not included in the latest release `0.18.0`.
> 
> You could try building the current `main` branch from source and see if it fixes the issue. Thanks!

Well, I tried installing dev version but links https://www.open3d.org/docs/latest/getting_started.html for Linux are broken :/

**Comment by rxba** [comment]
@iegorval You're right, I thought the links got fixed in a recent PR, but I am guessing something else is wrong with them currently. I also can't see the current Linux wheels on https://github.com/isl-org/Open3D/releases .

Unless someone else with more knowledge about the Releases can chime in, the only other advice I can give right now is to build the current main branch from source yourself, [according to the instructions](https://www.open3d.org/docs/latest/compilation.html).

**Comment by iegorval** [comment]
> @iegorval You're right, I thought the links got fixed in a recent PR, but I am guessing something else is wrong with them currently. I also can't see the current Linux wheels on https://github.com/isl-org/Open3D/releases .
> 
> Unless someone else with more knowledge about the Releases can chime in, the only other advice I can give right now is to build the current main branch from source yourself, [according to the instructions](https://www.open3d.org/docs/latest/compilation.html).

Ah, I see you answered message that I deleted.

Yes, the wheels did not work for me, I ended up building from source.

Somehow the method still does not do what I really expect. I ended up computing it with multiple combination of parameters to extract the surfaces I want even though all required surfaces had similar properties in terms of noise, normals etc. I am not sure if that is the fault of normals estimation itself or of this method. Even though I got the results, I am still not 100% convinced about this, because the change of parameters produces not-so-clear changes in results for me.

**Comment by iegorval** [comment]
> I haven't found the time to try it yet myself but thanks for the insights. If you have specific examples of how it is not working as intended feel free to post them so others can have a look.

Coming back to this topic: I am not even sure how it is intended to work. I have a point cloud with pretty visible planar patches located in the point cloud, and even after trying hundreds of combinations for the parameters of this algorithm, I am not able to detect them, while a lot of absolutely random non-planar things are getting marked as planar patches. So I would say either documentation / example is very unclear, or the method's quality is very dubious.

**Comment by chunibyo-wly** [comment]
@iegorval 
Could you provide some test data to help me figure out what happened?
