### ISSUE TITLE
Development wheels are no longer available

### ISSUE THREAD

**Issue by JorgePH** [isl-org/Open3D#7079]
### Checklist

- [X] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [X] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [X] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Steps to reproduce the issue

Try to download latest development wheel with:
```
pip install -U -f https://www.open3d.org/docs/latest/getting_started.html --only-binary open3d open3d
```
or
Go to the development links in https://www.open3d.org/docs/latest/getting_started.html#development-version-pip

### Error message

```shell
pip install -U -f https://www.open3d.org/docs/latest/getting_started.html --only-binary open3d open3d --break-system-packages
Looking in links: https://www.open3d.org/docs/latest/getting_started.html
Collecting open3d
  ERROR: HTTP error 404 while getting https://github.com/isl-org/Open3D/releases/download/main-devel/open3d-0.18.0%2Bb65896f-cp312-cp312-manylinux_2_31_x86_64.whl (from https://www.open3d.org/docs/latest/getting_started.html)
ERROR: Could not install requirement open3d from https://github.com/isl-org/Open3D/releases/download/main-devel/open3d-0.18.0%2Bb65896f-cp312-cp312-manylinux_2_31_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/isl-org/Open3D/releases/download/main-devel/open3d-0.18.0%2Bb65896f-cp312-cp312-manylinux_2_31_x86_64.whl for URL https://github.com/isl-org/Open3D/releases/download/main-devel/open3d-0.18.0%2Bb65896f-cp312-cp312-manylinux_2_31_x86_64.whl (from https://www.open3d.org/docs/latest/getting_started.html)
```

### Open3D, Python and System information

```markdown
- Operating system: ubuntu:noble official docker image
- Python version: Python 3.12.3
- Open3D version: Not installed, latest main commit (b65896f)
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip (development wheel)
- Compiler version (if built from source):
```

**Comment by JorgePH** [comment]
Last CICD run regenerated the files some of the files. Version for Python 3.12 is available now, but there are some others that are not. It seems the CICD job fails sometimes when uploading the binaries:

https://github.com/isl-org/Open3D/actions/runs/12063109780/job/33637787664#step:7:27

**Comment by Master-cai** [comment]
This problem still exists for python 3.9. The link in the offical website is 404.

**Comment by ssheorey** [comment]
CI is fixed. Available again.

**Comment by mschneider456** [comment]
Seems like the problem still persists for python3.9 under linux. No wheels are available [here](https://storage.googleapis.com/open3d-releases/python-wheels/open3d-0.18.0-cp39-cp39-manylinux_2_27_x86_64.whl) or [here](https://github.com/isl-org/Open3D/releases)

**Comment by JorgePH** [comment]
All the links in https://www.open3d.org/docs/latest/getting_started.html#development-version-pip are broken again

**Comment by fabiannagel** [comment]
+1, still an issue

**Comment by Danilrivero** [comment]
Can confirm the wheels are still not available as of now. Hopefully https://github.com/isl-org/Open3D/pull/7121 can solve this issue.

**Comment by ssheorey** [comment]
There's a clean release github action that cleans old devel releases - it seems to be over aggressive. I've disabled it for now.
